# Hardware related parameters
# will be loaded onto the parameter server
# See the auto_rover.launch
auto_rover:
  encoder_resolution: 2249 # 542249 # 5422248.86
  gain: 1.0
  trim: 0.0
  motor_constant: 1.0 #27.0
  pwm_limit: 1.0
  debug:
    hardware_interface: false
    base_controller: false